baseurl = "/"
languageCode = "en-uk"
theme = "terminal"
paginate = 5
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe= true

[params]
  description = "A collection of technical posts about programming, development and engineering."
  contentTypeName = "post"

  # default: orange; options: blue, green, pink, purple, red
  themeColor = "green"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Femto Blog"
    subtitle = ""
    keywords = ""
    copyright = "© Codefined"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found."
    missingBackButtonLabel = "Go Back"

    [languages.en.params.logo]
      logoText = "Femto Blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "post"
        name = "Posts"
        url = "/post"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
